export const FRONTEND_URL = 'https://scribeai.dev'
// const FRONTEND_URL = 'http:localhost:3000'
// const FRONTEND_URL = 'https://ba65-2401-4900-1c33-5b91-4819-49c4-101f-7c01.ngrok-free.app'

export const DEEPGRAMKEY = '8195de7ef8c12a670d9b893fd6b3a08779b010c1'
export const intervalsId = [];
export const transcriptionId = null;
export const firstApiCall = true;
export const count = 0;
export const icd_code_value = "";
export const isSearchedClick = false
export const patientData = null;
export const testType = null;

export const labelJson = {
    "app-title": "Intelidoc-AI",
    "page1-tab-title": "Transcript",
    "page1-main-title": "Meeting Transcript",
    "page1-highlight-message": "Double Click to highlight messages.",
    "page1-transcription-message": "Transcription will begin as soon as somebody talks...",
    "save": "Save",
    "pause": "Pause",
    "resume": "Resume",
    "reset": "Reset",
    "page2-tab-title": "Patient Insights",
    "page2-main-title": "Patient History",
    "page2-input-placeholder": "Patient Name",
    "page3-tab-title": "Settings",
    "speech-language-main-title": "Speech Language",
    "speech-language-sub-title": "You would need repoen on Language Change",
    "user-role-main-title": "User Role",
    "user-role-sub-title": "Select your role based on your identity",
    "auto-save-main-title": "Auto Save",
    "auto-save-sub-title": "This will Enable Auto-Save",
    "default-tab-main-title": "Default Tab",
    "default-tab-sub-title": "Tab that will be opened on Starting"
}

export const providerOptions = [
    { provider: 'OSOFSKY,DOUGLAS', speciality: "Podiatry" },
    { provider: 'VALENCIA,SHARON', speciality: "Podiatry" },
    { provider: 'TOBACK,TRACEY', speciality: "Podiatry" },
    { provider: 'ANTONETZ,THEODORE', speciality: "Podiatry" },
    { provider: 'SEECHARRAN,BONNIE', speciality: "Cardiology" },
    { provider: 'LOWENKRON,DAVID', speciality: "Cardiology" },
    { provider: 'SAHA,TISA', speciality: "Cardiology" },
    { provider: 'SINDHWANI,RAJEEV', speciality: "Cardiology" },
    { provider: 'MYUNG,YOON', speciality: "Ophthalmology" },
    { provider: 'MATTA,AYMAN', speciality: "Ophthalmology" },
    { provider: 'EL KHAYAT,MOUHAMED', speciality: "Ophthalmology" },
    { provider: 'MAMMO,REBECCA', speciality: "Ophthalmology" }
];

export const methodOptions = [
    { code: "E11.9", description: "Diabetes" },
    { code: "E11.01", description: "Type 2 diabetes mellitus with hyperosmolarity with coma" },
    { code: "E11.618", description: "Diabetes" },
    { code: "E11.40", description: "Diabetes" },
    { code: "E11.621", description: "Diabetes" },
    { code: "E11.51", description: "Diabetes" },
    { code: "E11.22", description: "Diabetes" },
    { code: "E11.69", description: "Diabetes" },
    { code: "E11.59", description: "Diabetes" },
    { code: "E13.9", description: "Diabetes 1.5, managed as type 1" },
    { code: "E10.9", description: "Diabetes 1.5, managed as type 1" },
    { code: "E13.9", description: "Diabetes 1.5, managed as type 2" },
    { code: "E10.9", description: "Diabetes 1.5, managed as type 2" },
    { code: "E11.9", description: "Diabetes" },
    { code: "E11.618", description: "Diabetes" },
    { code: "E11.40", description: "Diabetes" },
    { code: "E11.621", description: "Diabetes" },
    { code: "E11.51", description: "Diabetes" },
    { code: "E11.22", description: "Diabetes" },
    { code: "E11.69", description: "Diabetes" },
    { code: "E11.59", description: "Diabetes" },
    { code: "E13.9", description: "Diabetes 1.5, managed as type 1" },
    { code: "E10.9", description: "Diabetes 1.5, managed as type 1" },
    { code: "E13.9", description: "Diabetes 1.5, managed as type 2" },
    { code: "E10.9", description: "Diabetes 1.5, managed as type 2" },
    { code: "E08.40", description: "Diabetes due to underlying condition w diabetic neurop, unsp" },
    { code: "E08.22", description: "Diabetes due to undrl cond w diabetic chronic kidney disease" },
    { code: "Z71.89", description: "Diabetes education, encounter for" },
    { code: "O24.919", description: "Diabetes in preg-unspec" },
    { code: "O24.919", description: "Diabetes in pregnancy" },
    { code: "O24.911", description: "Diabetes in undelivered pregnancy, first trimester" },
    { code: "E23.2", description: "Diabetes insipidus" },
    { code: "E23.2", description: "Diabetes insipidus" },
    { code: "E23.2", description: "Diabetes insipidus secondary to vasopressin deficiency" },
    { code: "N25.1", description: "Diabetes insipidus, nephrogenic" },
    { code: "E23.2", description: "Diabetes insipidus, neurohypophyseal" },
    { code: "O24.92", description: "Diabetes mellitus affecting childbirth" },
    { code: "O24.911", description: "Diabetes mellitus affecting pregnancy in first trimester" },
    { code: "E11.69", description: "Diabetes mellitus associated with hormonal etiology" },
    { code: "E11.69", description: "Diabetes mellitus associated with receptor abnormality" },
    { code: "E11.9", description: "Diabetes mellitus case management patient" },
    { code: "O24.919", description: "Diabetes mellitus complicating pregnancy, antepartum" },
    { code: "E13.9", description: "Diabetes mellitus due to abnormal insulin" },
    { code: "E11.69", description: "Diabetes mellitus due to genetic disorder of beta cell function" },
    { code: "E13.9", description: "Diabetes mellitus due to genetic disorder of insulin action" },
    { code: "E11.9", description: "Diabetes mellitus due to insulin receptor antibodies" },
    { code: "E08.9", description: "Diabetes mellitus due to underlying condition" },
    { code: "E08.3213", description: "Diabetes mellitus due to underlying condition with both eyes affected by mild nonproliferative retinopathy and macular edema, without long-term current use of insulin" },
    { code: "E08.3393", description: "Diabetes mellitus due to underlying condition with both eyes affected by moderate nonproliferative retinopathy without macular edema, without long-term curre" },
    { code: "E08.3513", description: "Diabetes mellitus due to underlying condition with both eyes affected by retinopathy and macular edema, unspecified long term insulin use status, unspecified retinopathy severity" },
    { code: "E08.3413", description: "Diabetes mellitus due to underlying condition with both eyes affected by severe nonproliferative retinopathy and macular edema, without long-term current use of insulin" },
    { code: "E08.3493", description: "Diabetes mellitus due to underlying condition with both eyes affected by severe nonproliferative retinopathy without macular edema, without long-term current use of insulin" },
    { code: "E08.59", description: "Diabetes mellitus due to underlying condition with cardiac complication" },
    { code: "E08.36", description: "Diabetes mellitus due to underlying condition with cataract" },
    { code: "E08.22", description: "Diabetes mellitus due to underlying condition with chronic kidney disease, without long-term current use of insulin, unspecified CKD stage" },
    { code: "E08.59", description: "Diabetes mellitus due to underlying condition with circulatory complication" },
    { code: "E08.51", description: "Diabetes mellitus due to underlying condition with circulatory complication, with long-term current use of insulin" },
    { code: "E08.8", description: "Diabetes mellitus due to underlying condition with complication" },
    { code: "E08.8", description: "Diabetes mellitus due to underlying condition with complication, unspecified long term insulin use status" },
    { code: "E08.8", description: "Diabetes mellitus due to underlying condition with complication, unspecified whether long term insulin use" },
    { code: "E08.8", description: "Diabetes mellitus due to underlying condition with complication, without long-term current use of insulin" },
    { code: "E08.44", description: "Diabetes mellitus due to underlying condition with diabetic amyotrophy" },
    { code: "E08.618", description: "Diabetes mellitus due to underlying condition with diabetic arthropathy" },
    { code: "E08.43", description: "Diabetes mellitus due to underlying condition with diabetic autonomic (poly)neuropathy" },
    { code: "E08.43", description: "Diabetes mellitus due to underlying condition with diabetic autonomic neuropathy" },
    { code: "E08.43", description: "Diabetes mellitus due to underlying condition with diabetic autonomic neuropathy" },
    { code: "E08.43", description: "Diabetes mellitus due to underlying condition with diabetic autonomic neuropathy, unspecified whether long term insulin use" },
    { code: "E08.36", description: "Diabetes mellitus due to underlying condition with diabetic cataract" },
    { code: "E08.22", description: "Diabetes mellitus due to underlying condition with diabetic chronic kidney disease" },
    { code: "E08.22", description: "Diabetes mellitus due to underlying condition with diabetic chronic kidney disease, unspecified CKD stage, unspecified long term insulin use status" },
    { code: "E08.22", description: "Diabetes mellitus due to underlying condition with diabetic chronic kidney disease, unspecified CKD stage, unspecified whether long term insulin use" },
    { code: "E08.620", description: "Diabetes mellitus due to underlying condition with diabetic dermatitis" },
    { code: "E08.620", description: "Diabetes mellitus due to underlying condition with diabetic dermatitis, without long-term current use of insulin" },
    { code: "E08.37X3", description: "Diabetes mellitus due to underlying condition with diabetic macular edema, resolved following treatment, bilateral" },
    { code: "E08.37X2", description: "Diabetes mellitus due to underlying condition with diabetic macular edema, resolved following treatment, left eye" },
    { code: "E08.37X1", description: "Diabetes mellitus due to underlying condition with diabetic macular edema, resolved following treatment, right eye" },
    { code: "E08.37X9", description: "Diabetes mellitus due to underlying condition with diabetic macular edema, resolved following treatment, unspecified eye" },
    { code: "E08.41", description: "Diabetes mellitus due to underlying condition with diabetic mononeuropathy" },
    { code: "E08.21", description: "Diabetes mellitus due to underlying condition with diabetic nephropathy" },
    { code: "E08.21", description: "Diabetes mellitus due to underlying condition with diabetic nephropathy" },
    { code: "E08.21", description: "Diabetes mellitus due to underlying condition with diabetic nephropathy, unspecified whether long term insulin use" },
    { code: "E08.610", description: "Diabetes mellitus due to underlying condition with diabetic neuropathic arthropathy" },
    { code: "E08.40", description: "Diabetes mellitus due to underlying condition with diabetic neuropathy" },
    { code: "E08.40", description: "Diabetes mellitus due to underlying condition with diabetic neuropathy, unspecified" },
    { code: "E08.40", description: "Diabetes mellitus due to underlying condition with diabetic neuropathy, unspecified whether long term insulin use" },
    { code: "E08.40", description: "Diabetes mellitus due to underlying condition with diabetic neuropathy, without long-term current use of insulin" },
    { code: "E08.52", description: "Diabetes mellitus due to underlying condition with diabetic peripheral angiopathy with gangrene" },
    { code: "E08.51", description: "Diabetes mellitus due to underlying condition with diabetic peripheral angiopathy without gangrene" },
    { code: "E08.42", description: "Diabetes mellitus due to underlying condition with diabetic polyneuropathy" },
    { code: "E08.42", description: "Diabetes mellitus due to underlying condition with diabetic polyneuropathy" },
    { code: "E08.42", description: "Diabetes mellitus due to underlying condition with diabetic polyneuropathy" },
    { code: "E08.42", description: "Diabetes mellitus due to underlying condition with diabetic polyneuropathy, unspecified long term insulin use status" },
    { code: "E08.42", description: "Diabetes mellitus due to underlying condition with diabetic polyneuropathy, without long-term current use of insulin" },
    { code: "E08.319", description: "Diabetes mellitus due to underlying condition with diabetic retinopathy" },
    { code: "E08.621", description: "Diabetes mellitus due to underlying condition with foot ulcer" },
    { code: "E08.65", description: "Diabetes mellitus due to underlying condition with hyperglycemia" },
    { code: "E08.65", description: "Diabetes mellitus due to underlying condition with hyperglycemia, unspecified whether long term insulin use" },
    { code: "E08.65", description: "Diabetes mellitus due to underlying condition with hyperglycemia, without long-term current use of insulin" },
    { code: "E08.01", description: "Diabetes mellitus due to underlying condition with hyperosmolar coma, unspecified whether long term insulin use" },
    { code: "E08.01", description: "Diabetes mellitus due to underlying condition with hyperosmolarity with coma" },
    { code: "E08.00", description: "Diabetes mellitus due to underlying condition with hyperosmolarity without coma, without long-term current use of insulin" },
    { code: "E08.00", description: "Diabetes mellitus due to underlying condition with hyperosmolarity without nonketotic hyperglycemic-hyperosmolar coma (NKHHC)" },
    { code: "E08.649", description: "Diabetes mellitus due to underlying condition with hypoglycemia" },
    { code: "E08.641", description: "Diabetes mellitus due to underlying condition with hypoglycemia with coma" },
    { code: "E08.649", description: "Diabetes mellitus due to underlying condition with hypoglycemia without coma" },
    { code: "E08.649", description: "Diabetes mellitus due to underlying condition with hypoglycemia without coma, without long-term current use of insulin" },
    { code: "E08.11", description: "Diabetes mellitus due to underlying condition with ketoacidosis and coma, without long-term current use of insulin" },
    { code: "E08.11", description: "Diabetes mellitus due to underlying condition with ketoacidosis with coma" },
    { code: "E08.10", description: "Diabetes mellitus due to underlying condition with ketoacidosis without coma" },
    { code: "E08.10", description: "Diabetes mellitus due to underlying condition with ketoacidosis without coma, without long-term current use of insulin" },
    { code: "E08.11", description: "Diabetes mellitus due to underlying condition with ketoacidotic coma, unspecified whether long term insulin use" },
    { code: "E08.11", description: "Diabetes mellitus due to underlying condition with ketoacidotic coma, without long-term current use of insulin" },
    { code: "E08.3392", description: "Diabetes mellitus due to underlying condition with left eye affected by moderate nonproliferative retinopathy without macular edema, unspecified whether long term insulin use" },
    { code: "E08.3213", description: "Diabetes mellitus due to underlying condition with mild nonproliferative diabetic retinopathy with macular edema, bilateral" },
    { code: "E08.3212", description: "Diabetes mellitus due to underlying condition with mild nonproliferative diabetic retinopathy with macular edema, left eye" },
    { code: "E08.3211", description: "Diabetes mellitus due to underlying condition with mild nonproliferative diabetic retinopathy with macular edema, right eye" },
    { code: "E08.3219", description: "Diabetes mellitus due to underlying condition with mild nonproliferative diabetic retinopathy with macular edema, unspecified eye" },
    { code: "E08.3293", description: "Diabetes mellitus due to underlying condition with mild nonproliferative diabetic retinopathy without macular edema, bilateral" },
    { code: "E08.3292", description: "Diabetes mellitus due to underlying condition with mild nonproliferative diabetic retinopathy without macular edema, left eye" },
    { code: "E08.3291", description: "Diabetes mellitus due to underlying condition with mild nonproliferative diabetic retinopathy without macular edema, right eye" },
    { code: "E08.3299", description: "Diabetes mellitus due to underlying condition with mild nonproliferative diabetic retinopathy without macular edema, unspecified eye" },
    { code: "E08.3299", description: "Diabetes mellitus due to underlying condition with mild nonproliferative retinopathy without macular edema, unspecified laterality, unspecified whether long term insulin use" },
    { code: "E08.3299", description: "Diabetes mellitus due to underlying condition with mild nonproliferative retinopathy, macular edema presence unspecified, unspecified laterality, unspecified whether long term insulin use" },
    { code: "E08.3313", description: "Diabetes mellitus due to underlying condition with moderate nonproliferative diabetic retinopathy with macular edema, bilateral" },
    { code: "E08.3312", description: "Diabetes mellitus due to underlying condition with moderate nonproliferative diabetic retinopathy with macular edema, left eye" },
    { code: "E08.3311", description: "Diabetes mellitus due to underlying condition with moderate nonproliferative diabetic retinopathy with macular edema, right eye" },
    { code: "E08.3319", description: "Diabetes mellitus due to underlying condition with moderate nonproliferative diabetic retinopathy with macular edema, unspecified eye" },
    { code: "E08.3393", description: "Diabetes mellitus due to underlying condition with moderate nonproliferative diabetic retinopathy without macular edema, bilateral" },
    { code: "E08.3393", description: "Diabetes mellitus due to underlying condition with moderate nonproliferative diabetic retinopathy without macular edema, bilateral" },
    { code: "E08.3392", description: "Diabetes mellitus due to underlying condition with moderate nonproliferative diabetic retinopathy without macular edema, left eye" },
    { code: "E08.3392", description: "Diabetes mellitus due to underlying condition with moderate nonproliferative diabetic retinopathy without macular edema, left eye" },
    { code: "E08.3391", description: "Diabetes mellitus due to underlying condition with moderate nonproliferative diabetic retinopathy without macular edema, right eye" },
    { code: "E08.3391", description: "Diabetes mellitus due to underlying condition with moderate nonproliferative diabetic retinopathy without macular edema, right eye" },
    { code: "E08.3399", description: "Diabetes mellitus due to underlying condition with moderate nonproliferative diabetic retinopathy without macular edema, unspecified eye" },
    { code: "E08.3399", description: "Diabetes mellitus due to underlying condition with moderate nonproliferative diabetic retinopathy without macular edema, unspecified eye" },
    { code: "E08.3399", description: "Diabetes mellitus due to underlying condition with moderate nonproliferative retinopathy, without long-term current use of insulin, macular edema presence unspecified, unspecified laterality" },
    { code: "E08.59", description: "Diabetes mellitus due to underlying condition with other circulatory complication, unspecified whether long term insulin use" },
    { code: "E08.59", description: "Diabetes mellitus due to underlying condition with other circulatory complication, without long-term current use of insulin" },
    { code: "E08.59", description: "Diabetes mellitus due to underlying condition with other circulatory complications" },
    { code: "E08.618", description: "Diabetes mellitus due to underlying condition with other diabetic arthropathy" },
    { code: "E08.29", description: "Diabetes mellitus due to underlying condition with other diabetic kidney complication" },
    { code: "E08.49", description: "Diabetes mellitus due to underlying condition with other diabetic neurological complication" },
    { code: "E08.39", description: "Diabetes mellitus due to underlying condition with other diabetic ophthalmic complication" },
    { code: "E08.39", description: "Diabetes mellitus due to underlying condition with other ophthalmic complication" },
    { code: "E08.638", description: "Diabetes mellitus due to underlying condition with other oral complications" },
    { code: "E08.628", description: "Diabetes mellitus due to underlying condition with other skin complications" },
    { code: "E08.622", description: "Diabetes mellitus due to underlying condition with other skin ulcer" },
    { code: "E08.69", description: "Diabetes mellitus due to underlying condition with other specified complication" },
    { code: "E08.69", description: "Diabetes mellitus due to underlying condition with other specified complication, unspecified whether long term insulin use" },
    { code: "E08.69", description: "Diabetes mellitus due to underlying condition with other specified complication, without long-term current use of insulin" },
    { code: "E08.630", description: "Diabetes mellitus due to underlying condition with periodontal disease" },
    { code: "E08.3543", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, bilateral" },
    { code: "E08.3542", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, left eye" },
    { code: "E08.3541", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, right eye" },
    { code: "E08.3549", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, unspecified eye" },
    { code: "E08.3513", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with macular edema, bilateral" },
    { code: "E08.3512", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with macular edema, left eye" },
    { code: "E08.3511", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with macular edema, right eye" },
    { code: "E08.3519", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with macular edema, unspecified eye" },
    { code: "E08.3523", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with traction retinal detachment involving the macula, bilateral" },
    { code: "E08.3522", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with traction retinal detachment involving the macula, left eye" },
    { code: "E08.3521", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with traction retinal detachment involving the macula, right eye" },
    { code: "E08.3529", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with traction retinal detachment involving the macula, unspecified eye" },
    { code: "E08.3533", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, bilateral" },
    { code: "E08.3532", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, left eye" },
    { code: "E08.3531", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, right eye" },
    { code: "E08.3539", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, unspecified eye" },
    { code: "E08.3593", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy without macular edema, bilateral" },
    { code: "E08.3592", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy without macular edema, left eye" },
    { code: "E08.3591", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy without macular edema, right eye" },
    { code: "E08.3599", description: "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy without macular edema, unspecified eye" },
    { code: "E08.3413", description: "Diabetes mellitus due to underlying condition with severe nonproliferative diabetic retinopathy with macular edema, bilateral" },
    { code: "E08.3412", description: "Diabetes mellitus due to underlying condition with severe nonproliferative diabetic retinopathy with macular edema, left eye" },
    { code: "E08.3411", description: "Diabetes mellitus due to underlying condition with severe nonproliferative diabetic retinopathy with macular edema, right eye" },
    { code: "E08.3419", description: "Diabetes mellitus due to underlying condition with severe nonproliferative diabetic retinopathy with macular edema, unspecified eye" },
    { code: "E08.3493", description: "Diabetes mellitus due to underlying condition with severe nonproliferative diabetic retinopathy without macular edema, bilateral" },
    { code: "E08.3492", description: "Diabetes mellitus due to underlying condition with severe nonproliferative diabetic retinopathy without macular edema, left eye" },
    { code: "E08.3491", description: "Diabetes mellitus due to underlying condition with severe nonproliferative diabetic retinopathy without macular edema, right eye" },
    { code: "E08.3499", description: "Diabetes mellitus due to underlying condition with severe nonproliferative diabetic retinopathy without macular edema, unspecified eye" },
    { code: "E08.3553", description: "Diabetes mellitus due to underlying condition with stable proliferative diabetic retinopathy, bilateral" },
    { code: "E08.3552", description: "Diabetes mellitus due to underlying condition with stable proliferative diabetic retinopathy, left eye" },
    { code: "E08.3551", description: "Diabetes mellitus due to underlying condition with stable proliferative diabetic retinopathy, right eye" },
    { code: "E08.3559", description: "Diabetes mellitus due to underlying condition with stable proliferative diabetic retinopathy, unspecified eye" },
    { code: "E08.8", description: "Diabetes mellitus due to underlying condition with unspecified complications" },
    { code: "E08.311", description: "Diabetes mellitus due to underlying condition with unspecified diabetic retinopathy with macular edema" },
    { code: "E08.319", description: "Diabetes mellitus due to underlying condition with unspecified diabetic retinopathy without macular edema" },
    { code: "E08.319", description: "Diabetes mellitus due to underlying condition with unspecified diabetic retinopathy without macular edema" },
    { code: "E08.9", description: "Diabetes mellitus due to underlying condition without complication, unspecified long term insulin use status" },
    { code: "E08.9", description: "Diabetes mellitus due to underlying condition without complication, unspecified whether long term insulin use" },
    { code: "E08.9", description: "Diabetes mellitus due to underlying condition without complication, without long-term current use of insulin" },
    { code: "E08.9", description: "Diabetes mellitus due to underlying condition without complications" },
    { code: "E08.9", description: "Diabetes mellitus due to underlying condition without complications" },
    { code: "E08.51", description: "Diabetes mellitus due to underlying condition, controlled, with circulatory complication, with long-term current use of insulin" },
    { code: "E08.21", description: "Diabetes mellitus due to underlying condition, controlled, with diabetic nephropathy, without long-term current use of insulin" },
    { code: "E08.65", description: "Diabetes mellitus due to underlying condition, uncontrolled, with hyperglycemia" },
    { code: "E08.65", description: "Diabetes mellitus due to underlying condition, uncontrolled, with hyperglycemia, without long-term current use of insulin" },
    { code: "E08.00", description: "Diabetes mellitus due to underlying condition, uncontrolled, with hyperosmolarity without coma, without long-term current use of insulin" },
    { code: "Z91.89", description: "Diabetes mellitus high risk" },
    { code: "E13.8", description: "Diabetes mellitus of other type with complication, unspecified long term insulin use status" },
    { code: "E13.8", description: "Diabetes mellitus of other type with complication, unspecified whether long term insulin use" },
    { code: "E13.01", description: "Diabetes mellitus of other type with hyperosmolar coma" },
    { code: "E13.00", description: "Diabetes mellitus of other type with hyperosmolarity, without long-term current use of insulin" },
    { code: "E13.641", description: "Diabetes mellitus of other type with hypoglycemic coma, unspecified whether long term insulin use" },
    { code: "E13.10", description: "Diabetes mellitus of other type with ketoacidosis without coma, unspecified whether long term insulin use" },
    { code: "E13.10", description: "Diabetes mellitus of other type with ketoacidosis, without long-term current use of insulin" },
    { code: "E13.11", description: "Diabetes mellitus of other type with ketoacidotic coma, unspecified whether long term insulin use" },
    { code: "E13.3212", description: "Diabetes mellitus of other type with left eye affected by mild nonproliferative retinopathy and macular edema, unspecified whether long term insulin use" },
    { code: "E13.3292", description: "Diabetes mellitus of other type with left eye affected by mild nonproliferative retinopathy without macular edema, unspecified whether long term insulin use" },
    { code: "E13.3312", description: "Diabetes mellitus of other type with left eye affected by moderate nonproliferative retinopathy and macular edema, unspecified whether long term insulin use" },
    { code: "E13.3492", description: "Diabetes mellitus of other type with left eye affected by severe nonproliferative retinopathy without macular edema, without long-term current use of insulin" },
    { code: "E13.3291", description: "Diabetes mellitus of other type with mild nonproliferative retinopathy of right eye, without long-term current use of insulin, macular edema presence unspecified" },
    { code: "E13.29", description: "Diabetes mellitus of other type with other kidney complication, unspecified whether long term insulin use" },
    { code: "E13.39", description: "Diabetes mellitus of other type with other ophthalmic complication" },
    { code: "E13.3599", description: "Diabetes mellitus of other type with proliferative retinopathy, macular edema presence unspecified, unspecified laterality, unspecified proliferative retinopathy type, unspecified whether long term insulin use" },
    { code: "E13.319", description: "Diabetes mellitus of other type with retinopathy without macular edema, unspecified laterality, unspecified retinopathy severity, unspecified whether long term insulin use" },
    { code: "E13.319", description: "Diabetes mellitus of other type with retinopathy, macular edema presence unspecified, unspecified laterality, unspecified retinopathy severity, unspecified whether long term insulin use" },
    { code: "E13.319", description: "Diabetes mellitus of other type with retinopathy, macular edema presence unspecified, unspecified long term insulin use status, unspecified retinopathy severity" },
    { code: "E13.9", description: "Diabetes mellitus of other type without complication" },
    { code: "E13.9", description: "Diabetes mellitus of other type without complication, unspecified long term insulin use status" },
    { code: "E13.9", description: "Diabetes mellitus of other type without complication, unspecified whether long term insulin use" },
    { code: "Z13.1", description: "Diabetes mellitus screening" },
    { code: "Z53.20", description: "Diabetes mellitus screening declined by patient" },
    { code: "E11.9", description: "Diabetes mellitus treated with oral medication" },
    { code: "E10.9", description: "Diabetes mellitus Type 1" },
    { code: "E10.9", description: "Diabetes mellitus Type 1" },
    { code: "E10.9", description: "Diabetes mellitus Type 1" },
    { code: "E10.9", description: "Diabetes mellitus type 1, controlled, insulin dependent" },
    { code: "E13.9", description: "Diabetes mellitus type 1.5" },
    { code: "E13.9", description: "Diabetes mellitus type 1.5, managed as type 1" },
    { code: "E10.9", description: "Diabetes mellitus type 1.5, managed as type 1" },
    { code: "E13.9", description: "Diabetes mellitus type 1.5, managed as type 2" },
    { code: "E11.9", description: "Diabetes mellitus type 2 in nonobese" },
    { code: "E11.51", description: "Diabetes mellitus type 2 with atherosclerosis of arteries of extremities" },
    { code: "E11.8", description: "Diabetes mellitus type 2 with complications" },
    { code: "E11.10", description: "Diabetes mellitus type 2 with ketoacidosis, uncontrolled" },
    { code: "E11.49", description: "Diabetes mellitus type 2 with neurological manifestations" },
    { code: "E11.51", description: "Diabetes mellitus type 2 with peripheral artery disease" },
    { code: "E11.9", description: "Diabetes mellitus type 2 without retinopathy" },
    { code: "E11.9", description: "Diabetes mellitus type 2, diet-controlled" },
    { code: "E11.9", description: "Diabetes mellitus type 2, insulin dependent" },
    { code: "E11.9", description: "Diabetes mellitus type 2, noninsulin dependent" },
    { code: "E11.65", description: "Diabetes mellitus type 2, uncontrolled, without complications" },
    { code: "E10.9", description: "Diabetes mellitus Type I" },
    { code: "E10.9", description: "Diabetes mellitus Type I" },
    { code: "E11.9", description: "Diabetes mellitus type II, non insulin dependent" },
    { code: "E11.59", description: "Diabetes mellitus with cardiac complication" },
    { code: "E11.8", description: "Diabetes mellitus with complication" },
    { code: "E11.8", description: "Diabetes mellitus with complication in adult patient" },
    { code: "E11.8", description: "Diabetes mellitus with complication, with long-term current use of insulin" },
    { code: "E11.40", description: "Diabetes mellitus with diabetic neuropathy" },
    { code: "E11.9", description: "Diabetes mellitus with features of insulin resistance" },
    { code: "E11.43", description: "Diabetes mellitus with gastroparesis" },
    { code: "E11.9", description: "Diabetes mellitus with hemoglobin A1c goal of 7.0%-8.0%" },
    { code: "E11.00", description: "Diabetes mellitus with hyperosmolarity without hyperglycemic hyperosmolar nonketotic coma" },
    { code: "E11.9", description: "Diabetes mellitus with insulin therapy" },
    { code: "E13.10", description: "Diabetes mellitus with ketosis" },
    { code: "E11.21", description: "Diabetes mellitus with kidney disease" },
    { code: "E11.21", description: "Diabetes mellitus with macroalbuminuric diabetic nephropathy" },
    { code: "E11.8", description: "Diabetes mellitus with multiple complications" },
    { code: "E11.21", description: "Diabetes mellitus with nephropathy" },
    { code: "E11.40", description: "Diabetes mellitus with neuropathy" },
    { code: "E08.40", description: "Diabetes mellitus with neuropathy" },
    { code: "E11.00", description: "Diabetes mellitus with nonketotic hyperosmolarity" },
    { code: "E11.51", description: "Diabetes mellitus with peripheral angiopathy" },
    { code: "E11.51", description: "Diabetes mellitus with peripheral artery disease" },
    { code: "E11.51", description: "Diabetes mellitus with peripheral circulatory disorder" },
    { code: "E11.51", description: "Diabetes mellitus with peripheral vascular disease" },
    { code: "E11.21", description: "Diabetes mellitus with proteinuric diabetic nephropathy" },
    { code: "E11.22", description: "Diabetes mellitus with renal complications" },
    { code: "E11.9", description: "Diabetes mellitus without complication" },
    { code: "E11.9", description: "Diabetes mellitus without complication" },
    { code: "E11.9", description: "Diabetes mellitus without complication" },
    { code: "E11.9", description: "Diabetes mellitus, insulin dependent (IDDM), controlled" },
    { code: "E10.51", description: "Diabetes mellitus, insulin dependent (IDDM), uncontrolled" },
    { code: "E10.22", description: "Diabetes mellitus, insulin dependent (IDDM), uncontrolled" },
    { code: "E10.59", description: "Diabetes mellitus, insulin dependent (IDDM), uncontrolled" },
    { code: "E11.9", description: "Diabetes mellitus, new onset" },
    { code: "E11.9", description: "Diabetes mellitus, type II, insulin dependent" },
    { code: "E10.65", description: "Diabetes Type 1 w/hyperglycemia" },
    { code: "E11.9", description: "Diabetes type 2, no ocular involvement" },
    { code: "E11.65", description: "Diabetes type w/ hyperglycemia" },
    { code: "E11.319", description: "Diabetes with retinopathy" },
    { code: "E11.628", description: "Diabetes with skin complication" },
    { code: "E11.622", description: "Diabetes with ulcer of leg" },
    { code: "E13.9", description: "Diabetes, type 1.5, controlled, managed as type 2" },
    { code: "E10.9", description: "Diabetes, type 1.5, controlled, managed as type 2" },
    { code: "E13.65", description: "Diabetes, type 1.5, uncontrolled, managed as type 1" },
    { code: "E13.65", description: "Diabetes, type 1.5, uncontrolled, managed as type 2" },
    { code: "E11.9", description: "Abnormal metabolic state due to diabetes mellitus" },
    { code: "E11.22", description: "Type 2 diabetes mellitus" },
    { code: "E11.42", description: "Type 2 diabetes mellitus" },
    { code: "E11.59", description: "Type 2 diabetes mellitus" },
    { code: "E11.9", description: "Type 2 diabetes mellitus" },
    { code: "O24.111", description: "Type 2 diabetes mellitus affecting pregnancy in first trimester, antepartum" },
    { code: "O24.112", description: "Type 2 diabetes mellitus affecting pregnancy in second trimester, antepartum" },
    { code: "O24.113", description: "Type 2 diabetes mellitus affecting pregnancy in third trimester, antepartum" },
    { code: "O24.119", description: "Type 2 diabetes mellitus during pregnancy, antepartum" },
    { code: "E11.65", description: "Type 2 diabetes mellitus w/ hyperglcemia" },
    { code: "E11.43", description: "Type 2 diabetes mellitus with autonomic neuropathy, unspecified long term insulin use status" },
    { code: "E11.3213", description: "Type 2 diabetes mellitus with both eyes affected by mild nonproliferative retinopathy and macular edema, without long-term current use of insulin" },
    { code: "E11.3293", description: "Type 2 diabetes mellitus with both eyes affected by mild nonproliferative retinopathy without macular edema, without long-term current use of insulin" },
    { code: "E11.3313", description: "Type 2 diabetes mellitus with both eyes affected by moderate nonproliferative retinopathy and macular edema, without long-term current use of insulin" },
    { code: "E11.3393", description: "Type 2 diabetes mellitus with both eyes affected by moderate nonproliferative retinopathy without macular edema, without long-term current use of insulin" },
    { code: "E11.3513", description: "Type 2 diabetes mellitus with both eyes affected by proliferative retinopathy and macular edema, without long-term current use of insulin" },
    { code: "E11.3523", description: "Type 2 diabetes mellitus with both eyes affected by proliferative retinopathy and traction retinal detachments involving maculae, unspecified whether long term insulin use" },
    { code: "E11.3593", description: "Type 2 diabetes mellitus with both eyes affected by proliferative retinopathy without macular edema, without long-term current use of insulin" },
    { code: "E11.311", description: "Type 2 diabetes mellitus with both eyes affected by retinopathy and macular edema, without long-term current use of insulin, unspecified retinopathy severity" },
    { code: "E11.319", description: "Type 2 diabetes mellitus with both eyes affected by retinopathy without macular edema, without long-term current use of insulin, unspecified retinopathy severity" },
    { code: "E11.3413", description: "Type 2 diabetes mellitus with both eyes affected by severe nonproliferative retinopathy and macular edema, without long-term current use of insulin" },
    { code: "E11.3493", description: "Type 2 diabetes mellitus with both eyes affected by severe nonproliferative retinopathy without macular edema, without long-term current use of insulin" },
    { code: "E11.610", description: "Type 2 diabetes mellitus with Charcot's joint of left foot" },
    { code: "E11.8", description: "Type 2 diabetes mellitus with complication" },
    { code: "E11.44", description: "Type 2 diabetes mellitus with diabetic amyotrophy" },
    { code: "E11.36", description: "Type 2 diabetes mellitus with diabetic cataract" },
    { code: "E11.618", description: "Type 2 diabetes mellitus with diabetic cheirarthropathy" },
    { code: "E11.620", description: "Type 2 diabetes mellitus with diabetic dermatitis" },
    { code: "E11.37X3", description: "Type 2 diabetes mellitus with diabetic macular edema of both eyes resolved after treatment, unspecified long term insulin use status" },
    { code: "E11.37X1", description: "Type 2 diabetes mellitus with diabetic macular edema of right eye resolved after treatment, without long-term current use of insulin" },
    { code: "E11.37X2", description: "Type 2 diabetes mellitus with diabetic macular edema, resolved following treatment, left eye" },
    { code: "E11.37X9", description: "Type 2 diabetes mellitus with diabetic macular edema, resolved following treatment, unspecified eye" },
    { code: "E11.41", description: "Type 2 diabetes mellitus with diabetic mononeuropathy" },
    { code: "E11.21", description: "Type 2 diabetes mellitus with diabetic nephropathy" },
    { code: "E11.40", description: "Type 2 diabetes mellitus with diabetic neuropathy, unspecified" },
    { code: "E11.52", description: "Type 2 diabetes mellitus with diabetic peripheral angiopathy and gangrene, without long-term current use of insulin" },
    { code: "E11.51", description: "Type 2 diabetes mellitus with diabetic peripheral angiopathy without gangrene" },
    { code: "E11.621", description: "Type 2 diabetes mellitus with foot ulcer" },
    { code: "E11.01", description: "Type 2 diabetes mellitus with hyperglycemic coma" },
    { code: "E11.01", description: "Type 2 diabetes mellitus with hyperosmolar coma, without long-term current use of insulin" },
    { code: "E11.00", description: "Type 2 diabetes mellitus with hyperosmolarity without coma, unspecified long term insulin use status" },
    { code: "E11.641", description: "Type 2 diabetes mellitus with hypoglycemia and coma, without long-term current use of insulin" },
    { code: "E11.649", description: "Type 2 diabetes mellitus with hypoglycemia without coma" },
    { code: "E11.11", description: "Type 2 diabetes mellitus with ketoacidosis with coma" },
    { code: "E11.10", description: "Type 2 diabetes mellitus with ketoacidosis without coma" },
    { code: "E13.10", description: "Type 2 diabetes mellitus with ketoacidosis without coma, unspecified long term insulin use status" },
    { code: "E11.3292", description: "Type 2 diabetes mellitus with left eye affected by mild nonproliferative retinopathy without macular edema, without long-term current use of insulin" },
    { code: "E11.3312", description: "Type 2 diabetes mellitus with left eye affected by moderate nonproliferative retinopathy and macular edema, without long-term current use of insulin" },
    { code: "E11.3512", description: "Type 2 diabetes mellitus with left eye affected by proliferative retinopathy and macular edema, without long-term current use of insulin" },
    { code: "E11.3522", description: "Type 2 diabetes mellitus with left eye affected by proliferative retinopathy and traction retinal detachment involving macula, unspecified whether long term insulin use" },
    { code: "E11.3592", description: "Type 2 diabetes mellitus with left eye affected by proliferative retinopathy without macular edema, without long-term current use of insulin" },
    { code: "E11.3212", description: "Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, left eye" },
    { code: "E11.3211", description: "Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, right eye" },
    { code: "E11.3219", description: "Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, unspecified eye" },
    { code: "E11.3291", description: "Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, right eye" },
    { code: "E11.3299", description: "Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, unspecified eye" },
    { code: "E11.3391", description: "Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy of right eye without macular edema, unspecified long term insulin use status" },
    { code: "E11.3311", description: "Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, right eye" },
    { code: "E11.3319", description: "Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, unspecified eye" },
    { code: "E11.3392", description: "Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, left eye" },
    { code: "E11.3399", description: "Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, unspecified eye" },
    { code: "E11.49", description: "Type 2 diabetes mellitus with neurological manifestations, controlled" },
    { code: "11.618", description: "Type 2 diabetes mellitus with other diabetic arthropathy, unspecified whether long term insulin use" },
    { code: "E11.29", description: "Type 2 diabetes mellitus with other diabetic kidney complication" },
    { code: "E11.39", description: "Type 2 diabetes mellitus with other diabetic ophthalmic complication" },
    { code: "E11.638", description: "Type 2 diabetes mellitus with other oral complication, unspecified whether long term insulin use" },
    { code: "E11.628", description: "Type 2 diabetes mellitus with other skin complication, unspecified whether long term insulin use" },
    { code: "E11.622", description: "Type 2 diabetes mellitus with other skin ulcer" },
    { code: "E11.69", description: "Type 2 diabetes mellitus with other specified complication" },
    { code: "E11.630", description: "Type 2 diabetes mellitus with periodontal disease" },
    { code: "E11.3499", description: "Type 2 diabetes mellitus with preproliferative retinopathy" },
    { code: "E11.3543", description: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, bilateral" },
    { code: "E11.3542", description: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, left eye" },
    { code: "E11.3541", description: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, right eye" },
    { code: "E11.3549", description: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, unspecified eye" },
    { code: "E11.3511", description: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with macular edema, right eye" },
    { code: "E11.3519", description: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with macular edema, unspecified eye" },
    { code: "E11.3521", description: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, right eye" },
    { code: "E11.3529", description: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, unspecified eye" },
    { code: "E11.3533", description: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, bilateral" },
    { code: "E11.3532", description: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, left eye" },
    { code: "E11.3531", description: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, right eye" },
    { code: "E11.3539", description: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, unspecified eye" },
    { code: "E11.3591", description: "Type 2 diabetes mellitus with proliferative diabetic retinopathy without macular edema, right eye" },
    { code: "E11.3599", description: "Type 2 diabetes mellitus with proliferative diabetic retinopathy without macular edema, unspecified eye" },
    { code: "E11.3412", description: "Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, left eye" },
    { code: "E11.3411", description: "Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, right eye" },
    { code: "E11.3419", description: "Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, unspecified eye" },
    { code: "E11.3492", description: "Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, left eye" },
    { code: "E11.3491", description: "Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, right eye" },
    { code: "E11.3553", description: "Type 2 diabetes mellitus with stable proliferative diabetic retinopathy, bilateral" },
    { code: "E11.3552", description: "Type 2 diabetes mellitus with stable proliferative diabetic retinopathy, left eye" },
    { code: "E11.3551", description: "Type 2 diabetes mellitus with stable proliferative diabetic retinopathy, right eye" },
    { code: "E11.3559", description: "Type 2 diabetes mellitus with stable proliferative diabetic retinopathy, unspecified eye" },
    { code: "S32.15XA", description: "Type 2 fracture of sacrum, initial encounter for closed fracture" },
    { code: "S32.15XB", description: "Type 2 fracture of sacrum, initial encounter for open fracture" },
    { code: "S32.15XS", description: "Type 2 fracture of sacrum, sequela" },
    { code: "S32.15XG", description: "Type 2 fracture of sacrum, subsequent encounter for fracture with delayed healing" },
    { code: "S32.15XK", description: "Type 2 fracture of sacrum, subsequent encounter for fracture with nonunion" },
    { code: "S32.15XD", description: "Type 2 fracture of sacrum, subsequent encounter for fracture with routine healing" },
    { code: "A60.01", description: "Type 2 herpes simplex infection of penis" },
    { code: "A60.04", description: "Type 2 HSV infection of vulvovaginal region" },
    { code: "I21.A1", description: "Type 2 MI (myocardial infarction)" },
    { code: "S43.432A", description: "Type 2 superior labrum extending from anterior to posterior (SLAP) lesion of left shoulder, initial encounter" },
    { code: "S43.432D", description: "Type 2 superior labrum extending from anterior to posterior (SLAP) lesion of left shoulder, subsequent encounter" }
]

export const specialityOptions = [
    { speciality: "Podiatry" },
    { speciality: "Cardiology" },
    { speciality: "Ophthalmology" }
];

export const ImmOptions = [
    { type: "Pneumovax 23" },
    { type: "Prevnar 20" },
];

export const sleepStudyOptions = [
    { type: "In-Office Sleep Study" },
    { type: "Home Sleep Study" },
];